CREATE TABLE `dondh` (
  `SoDH` INT NOT NULL AUTO_INCREMENT,
  `NgayDH` DATETIME NULL,
  PRIMARY KEY (`SoDH`));
  
  CREATE TABLE `nhacc` (
  `MaNCC` INT NOT NULL AUTO_INCREMENT,
  `TenNCC` VARCHAR(45) NOT NULL,
  `DiaChi` VARCHAR(45) NOT NULL,
  `SoDT` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MaNCC`));
  
  CREATE TABLE `phieuxuat` (
  `SoPX` INT NOT NULL AUTO_INCREMENT,
  `NgayXuat` DATETIME NOT NULL,
  PRIMARY KEY (`SoPX`));
  
  CREATE TABLE `phieunhap` (
  `SoPN` INT NOT NULL AUTO_INCREMENT,
  `NhayNhap` DATETIME NOT NULL,
  PRIMARY KEY (`SoPN`));

CREATE TABLE `vattu` (
  `MaVTU` INT NOT NULL AUTO_INCREMENT,
  `TenVTU` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MaVTU`));
  
  CREATE TABLE `dondathang`.`thuoc1` (
  `DGXUAT` FLOAT NOT NULL,
  `SLXUAT` INT NOT NULL);
  
  CREATE TABLE `dondathang`.`thuoc2` (
  `DGNHAP` FLOAT NOT NULL,
  `SLNHAP` INT NOT NULL);
